class UserStates:
    Showing_Main_Menu = "Showing Main Menu"
    New_Khatma_Waiting_For_Opener_Name = "New Khatma Waiting For Opener Name"
    New_Khatma_Waiting_For_Intention = "New Khatma Waiting For Intention"
    New_Khatma_Waiting_For_Part_Duration = "New Khatma Waiting For Part Duration"
    New_Khatma_Waiting_For_Khatma_Type = "New Khatma Waiting For Khatma Type"
    New_Khatma_Waiting_For_Khatma_Confirmation = "New Khatma Waiting For Khatma Confirmation"
    Contribute_Khatma_Waiting_Type = "Contribute Khatma Waiting Type"
    Contribute_Private_Khatma_Waiting_ID = "Contribute Private Khatma Waiting ID"
    Contribute_Public_Khatma_Menu = "Contribute Public Khatma Menu"
    Nothing = "Nothing"
    Current_Contribution_Waiting_Type = "Contribute Khatma Waiting Type"
    Update_Khatma_Waiting_For_Opener_Name = "Update Khatma Waiting For Opener Name"
    Update_Khatma_Waiting_For_Intention = "Update Khatma Waiting For Intention"
    Update_Khatma_Waiting_For_Part_Duration = "Update Khatma Waiting For Part Duration"
    Update_Khatma_Waiting_For_Khatma_Type = "Update Khatma Waiting For Khatma Type"
    Browse_Quran_Waiting_For_Page_No = "Browse Quran Waiting For Page No"
